DELETE http://localhost:8888/api/self/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0bmFtZTMiLCJpYXQiOjE2NDE5MDQ2NDAsImV4cCI6MTY0MTkwNTY0MH0.6KAq9KCzmYD9Defa7J46JNRiquYuZPYneXhvnO11xFrhx8RsKIQ-qK-ZSPJa5EGgMCWZchmZ7JCuUOjC423c4w

