DELETE http://localhost:8888/api/self/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0bmFtZTQiLCJpYXQiOjE2NDA4NDc1OTQsImV4cCI6MTY0MDg0ODU5NH0.WlTL-svDzvfz-Ru4ka9DZufE9bcCTeS_PJa5bncK8k5BfhrPiRk8GX2R7y_nKbEFTYtDUh8nbWV9ttu475fnmg

