### 取得
GET http://localhost:8888/api/favorites/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0bmFtZTQiLCJpYXQiOjE2NDE5MDA5NzMsImV4cCI6MTY0MTkwMTk3M30.su7BbuzR5NMJM18TdMfkY_v9PLnw27Pi3-jy3zFAgMi1YngaldKVFLmUfILjpsDkkiR0QRF65e_wGawnAC4InQ



### 登録
POST http://localhost:8888/api/favorites/add/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0bmFtZTQiLCJpYXQiOjE2NDE5MDA5NzMsImV4cCI6MTY0MTkwMTk3M30.su7BbuzR5NMJM18TdMfkY_v9PLnw27Pi3-jy3zFAgMi1YngaldKVFLmUfILjpsDkkiR0QRF65e_wGawnAC4InQ



### 削除
POST http://localhost:8888/api/favorites/delete/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0bmFtZTQiLCJpYXQiOjE2NDE5MDA5NzMsImV4cCI6MTY0MTkwMTk3M30.su7BbuzR5NMJM18TdMfkY_v9PLnw27Pi3-jy3zFAgMi1YngaldKVFLmUfILjpsDkkiR0QRF65e_wGawnAC4InQ