PUT http://localhost:8888/api/posts/16
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0bmFtZTQiLCJpYXQiOjE2NDEwOTg5MDIsImV4cCI6MTY0MTA5OTkwMn0.HwPP6CLauxqC9vUvnwHVOfngUBCYXIENl2mY0Ar0Bz8pL9ximmiFhCR7j69ifb7lVOwE8KjTkNzABpObS_aYZw

{
  "title": "testname4: title updated",
  "content": "testname4: content updated",
  "expose": true
}
